PROMPTS = {
    "c4/calculator":
        "Your task is to add calls to a Calculator API to a piece of text. "
        "The calls should help you get information required to complete the text. "
        "You can call the API by writing \" [ Calculator(expression) ] \" "
        "where \"expression\" is the expression to be computed. "
        "Here are some examples of API calls:\n"
        "Input: The number in the next term is 18 + 12 x 3 = 54.\n"
        "Output: The number in the next term is 18 + 12 x 3 = [ Calculator(18 + 12 * 3) ] 54.\n"
        "\n"
        "Input: The population is 658,893 people. This is 11.4% of the national average of "
        "5,763,868 people.\n"
        "Output: The population is 658,893 people. This is 11.4% of the national average of "
        "[ Calculator(658,893 / 11.4%) ] 5,763,868 people.\n"
        "\n"
        "Input: A total of 252 qualifying matches were played, and 723 goals were scored (an "
        "average of 2.87 per match). This is twenty goals more than the 703 goals last year.\n"
        "Output: A total of 252 qualifying matches were played, and 723 goals were scored (an "
        "average of [ Calculator(723 / 252) ] 2.87 per match). This is twenty goals more than "
        "the [ Calculator(723 - 20) ] 703 goals last year.\n"
        "\n"
        "Input: I went to Paris in 1994 and stayed there until 2011, so in total, it was 17 years.\n"
        "Output: I went to Paris in 1994 and stayed there until 2011, so in total, it was "
        "[ Calculator(2011 - 1994) ] 17 years.\n"
        "\n"
        "Input: From this, we have 4 * 30 minutes = 120 minutes.\n"
        "Output: From this, we have 4 * 30 minutes = [ Calculator(4 * 30) ] 120 minutes.\n"
        "\n",
    "c4/qa":
        "Your task is to add calls to a Question Answering API to a piece of text. "
        "The questions should help you get information required to complete the text. "
        "You can call the API by writing \" [ QA(question) ] \" "
        "where \"question\" is the question you want to ask. "
        "Here are some examples of API calls:\n"
        "\n"
        "Input: Joe Biden was born in Scranton, Pennsylvania.\n"
        "Output: Joe Biden was born in [ QA(Where was Joe Biden born?) ] Scranton, Pennsylvania.\n"
        "\n"
        "Input: Coca-Cola, or Coke, is a carbonated soft drink manufactured by the Coca-Cola Company.\n"
        "Output: Coca-Cola, or Coke, is a carbonated soft drink manufactured by [ QA(Who manufactures Coca-Cola?) ] "
        "the Coca-Cola Company.\n"
        "\n",
    "c4/search":
        "Your task is to complete a given piece of text. You can use a Wikipedia Search API to look up information. "
        "You can do so by writing \" [ WikiSearch(term) ] \" where \"term\" is the search term you want to look up. "
        "Here are some examples of API calls:\n"
        "\n"
        "Input: The colors on the flag of Ghana have the following meanings: red is for the blood of martyrs, "
        "green for forests, and gold for mineral wealth.\n"
        "Output: The colors on the flag of Ghana have the following meanings: "
        "red is for [ WikiSearch(Ghana flag red meaning) ] the blood of martyrs, green for forests, "
        "and gold for mineral wealth.\n"
        "\n"
        "Input: But what are the risks during production of nanomaterials? "
        "Some nanomaterials may give rise to various kinds of lung damage.\n"
        "Output: But what are the risks during production of nanomaterials? "
        "[ WikiSearch(nanomaterial production risks) ] "
        "Some nanomaterials may give rise to various kinds of lung damage.\n"
        "\n"
        "Input: Metformin is the first-line drug for patients with type 2 diabetes and obesity.\n"
        "Output: Metformin is the first-line drug for [ WikiSearch(Metformin first-line drug) ] "
        "patients with type 2 diabetes and obesity.\n"
        "\n",
    "c4/translator":
        "Your task is to detect the non-English part of a text and translate the part using Machine Translation API. "
        "You can do so by writing \" [ MT(text) ] \" where text is the non-English part to be translated into English. "
        "Here are some examples:\n"
        "\n"
        "Input: He has published one book: O homem suprimido.\n"
        "Output: He has published one book: O homem suprimido [ MT(O homem suprimido) ].\n"
        "\n"
        "Input: 南京高淳县住房和城乡建设局 城市新区设计 a plane of reference Gaochun is one of seven districts "
        "of the provincial capital Nanjing.\n"
        "Output: 南京高淳县住房和城乡建设局 城市新区设计 [ MT(南京高淳县住房和城乡建设局 城市新区设计) ] a plane of reference "
        "Gaochun is one of seven districts of the provincial capital Nanjing.\n"
        "\n",
    "c4/calendar":
        "Your task is to add calls to a Calendar API to a piece of text. "
        "The API calls should help you get information required to complete the text. "
        "You can call the API by writing \" [ Calendar(dates) ] \" "
        "where \"dates\" could be \"today\", some date like \"1998-12-25\" or "
        "national holidays like \"New Year's Day\", \"Christmas\", \"Thanksgiving\" and \"Columbus Day\""
        "Here are some examples of API calls:\n"
        "\n"
        "Input: The current day of the week is Wednesday.\n"
        "Output: The current [ Calendar(today) ] day of the week is Wednesday.\n"
        "\n"
        "Input: The number of days from now until Independence Day is 30.\n"
        "Output: The number of days from now until Christmas [ Calendar(today, Independence Day) ] is 30.\n"
        "\n"
        "Input: Today is 1998-12-25, and it is Christmas.\n"
        "Output: Today is 1998-12-25, and it is Christmas [ Calendar(1998-12-25,Christmas) ].\n"
        "\n"
}
